version: "3"
services:
  nginx:
    image: nginx-simple:latest
    container_name: landing-page
    restart: always
    ports:
      - "9999:80"
    expose:
      - "80"
    volumes:
      - ./:/var/www/
    build:
      context: .
networks:
  default:
    external:
      name: nginx-proxy